general.import = [ 
  "C:\\Users\\pox\\AppData\\Roaming\\alacritty\\catppuccin-mocha.toml" 
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetbrainsMono Nerd Font Mono" }
bold = { family = "JetbrainsMono Nerd Font Mono" , style = "Bold"}
size = 15

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
#opacity = 0.9
#blur = true
startup_mode = "Maximized"
decorations = "none"

[terminal.shell]
  program = "wsl"
  args = ["--cd", "~"]

[mouse]
hide_when_typing = true
