"$schema" = 'https://starship.rs/config-schema.json'
right_format = """$cmd_duration"""
format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[character]
success_symbol = '[󰘧](bold green)'
error_symbol = '[󰘧](bold red)'
vimcmd_symbol = '[󰘧](bold green)'
vimcmd_replace_one_symbol = '[󰘧](bold purple)'
vimcmd_replace_symbol = '[󰘧](bold purple)'
vimcmd_visual_symbol = '[󰘧](bold yellow)'

[directory]
truncate_to_repo = true
style = 'bold bright-grey'

[git_branch]
format = '[git:$branch(:$remote_branch)]($style)'
style = 'bold #5C6370'

[git_status]
format = '([$all_status$ahead_behind]($style))'

[cmd_duration]
format = ' [$duration]($style)'
