CompileFlags:
  Add: [
    -I../include,
    -DLOCAL,
    -Wall,
    -Wextra,
    -Wconversion,
    -Wsign-conversion,
    -Wunreachable-code
    -Wshadow,
    -Wcast-qual,
    -Wcast-align,
    -Wformat=2,
    -Wundef,
    -Wmissing-prototypes,
    -Wattributes,
    -Wimplicit-int,
    -Wimplicit-function-declaration,
    -Wincompatible-pointer-types,
    -Wint-conversion,
    -Wmain,
    -Wpointer-arith,
    -Wpointer-sign,
    -Wincompatible-pointer-types,
  ]

Diagnostics:
  UnusedIncludes: Strict

Completion:
  ArgumentLists: Delimiters

InlayHints:
  ParameterNames: true
  DeducedTypes: true
  Designators: true
  BlockEnd: true
  DefaultArguments: true

Documentation:
  CommentFormat: Doxygen

