#!/usr/bin/env bash

wbDir=$HOME/.config/waybar
change_style () {
	style=$(ls $wbDir/styles/ | sed "s|\.css||g" | rofi -i -dmenu)
	unlink $wbDir/style.css
	echo "@import \"theme.css\";" > $wbDir/style.css
	echo "@import \"./styles/$style.css\";" >> $wbDir/style.css
	update_waybar
}

change_config() {
	config=$(ls $wbDir/configs/ | sed "s|\.jsonc||g" | rofi -i -dmenu)
	unlink $wbDir/config.jsonc
	ln -s $wbDir/configs/"$config".jsonc $wbDir/config.jsonc
	update_waybar
}

change_theme() {
	theme=$(ls $wbDir/themes/ | sed "s|\.css||g" | rofi -i -dmenu)
	unlink $wbDir/theme.css
	ln -s $wbDir/themes/$theme.css $wbDir/theme.css
	update_waybar
}

update_waybar() {
	if pgrep -x "waybar" > /dev/null; then
		killall waybar >/dev/null 2>&1
		setsid uwsm app -- /usr/bin/waybar >/dev/null 2>&1 & disown
	else
		setsid uwsm app -- /usr/bin/waybar >/dev/null 2>&1 & disown
	fi
}

user_choice=$(printf "Change Config\nChange Style\nChange Theme" | rofi -dmenu)
echo "User choice: $user_choice"
case "$user_choice" in
	"Change Theme")
		change_theme
		;;
	"Change Style")
		change_style
		;;
	"Change Config")
		change_config
		;;
	*)
		;;
esac

