return {
	"nvim-treesitter/nvim-treesitter",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").install({
			"java",
			"javadoc",
			"javascript",
			"typescript",
			"jsx",
			"tsx",
			"go",
			"rust",
			"zig",
			"bash",
			"c",
			"diff",
			"html",
			"css",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"query",
			"vim",
			"vimdoc",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
		})
	end,
}
